pipeline {
    agent {
        kubernetes {
            yaml """
            apiVersion: v1
            kind: Pod
            spec:
              containers:
              - name: maven
                image: maven:3.9.3-eclipse-temurin-17
                command: ['cat']
                tty: true
              - name: dind-daemon
                image: docker:20.10.12-dind
                securityContext:
                  privileged: true
                volumeMounts:
                - name: docker-graph-storage
                  mountPath: /var/lib/docker
              volumes:
              - name: docker-graph-storage
                emptyDir: {}
            """
        }
    }
    environment {
        DOCKER_HOST = 'tcp://localhost:2375'
    }
    stages {
        stage('Build') {
            steps {
                container('maven') {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                container('maven') {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                container('maven') {
                    sh './jenkins/scripts/deliver.sh'
                }
            }
        }
        stage('Complete') {
            steps {
                sh 'echo complete stage'
            }
        }
    }
}
